In [1]:
# Reading the cleaned numeric car prices data
import pandas as pd
import numpy as np

# To remove the scientific notation from numpy arrays
np.set_printoptions(suppress=True)

CarPricesDataNumeric=pd.read_pickle('CarPricesData.pkl')
CarPricesDataNumeric.head()

Age     KM  Weight  HP  MetColor      CC  Doors  Price
0  23.0  46986  1165.0  90         1  2000.0      3  13500
1  23.0  72937  1165.0  90         1  2000.0      3  13750
2  24.0  41711  1165.0  90         1  2000.0      3  13950
3  26.0  48000  1165.0  90         0  2000.0      3  14950
4  30.0  38500  1170.0  90         0  2000.0      3  13750

In [2]:
# Separate Target Variable and Predictor Variables
TargetVariable=['Price']
Predictors=['Age', 'KM', 'Weight', 'HP', 'MetColor', 'CC', 'Doors']

X=CarPricesDataNumeric[Predictors].values
y=CarPricesDataNumeric[TargetVariable].values

### Sandardization of data ###
from sklearn.preprocessing import StandardScaler
PredictorScaler=StandardScaler()
TargetVarScaler=StandardScaler()

# Storing the fit object for later reference
PredictorScalerFit=PredictorScaler.fit(X)
TargetVarScalerFit=TargetVarScaler.fit(y)

# Generating the standardized values of X and y
X=PredictorScalerFit.transform(X)
y=TargetVarScalerFit.transform(y)

# Split the data into training and testing set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Quick sanity check with the shapes of Training and testing datasets
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(1004, 7)
(1004, 1)
(431, 7)
(431, 1)


In [3]:
# importing the libraries
from unicodedata import name
from keras.models import Sequential
from keras.layers import Dense



In [4]:
# create ANN model
model = Sequential()

# Defining the Input layer and FIRST hidden layer, both are same!
model.add(Dense(units=5, input_dim=7, kernel_initializer='normal', activation='relu'))

# Defining the Second layer of the model
# after the first layer we don't have to specify input_dim as keras configure it automatically
model.add(Dense(units=5, kernel_initializer='normal', activation='tanh'))

# The output neuron is a single fully connected node 
# Since we will be predicting a single number
model.add(Dense(1, kernel_initializer='normal'))

# Compiling the model



In [30]:
model.get_weights()

[array([[ 0.31831685,  0.33394933, -0.43750423, -0.33683425,  0.3786552 ],
        [ 0.15994962,  0.20965905, -0.28070065, -0.36201048,  0.18956943],
        [-0.18329208, -0.12423095,  0.2913063 ,  0.31535178, -0.04884465],
        [-0.06690186, -0.06780812,  0.14852418,  0.09489351, -0.05890552],
        [ 0.0269471 ,  0.07935409,  0.06390228,  0.03016863, -0.04313393],
        [ 0.02171175,  0.04511083,  0.08256464,  0.06256074,  0.05368106],
        [-0.02971505, -0.03649281,  0.00358103,  0.03395367,  0.07648739]],
       dtype=float32),
 array([0.3334251 , 0.3289941 , 0.18815829, 0.17101094, 0.3210736 ],
       dtype=float32),
 array([[ 0.21091138,  0.24533753,  0.23165822, -0.27847084,  0.26929978],
        [ 0.15186447,  0.2310069 ,  0.26374274, -0.24854128,  0.23394798],
        [-0.38414374, -0.3470676 , -0.3360146 ,  0.2916963 , -0.27829722],
        [-0.3294085 , -0.33712414, -0.29864788,  0.2486087 , -0.31739637],
        [ 0.14373732,  0.21956322,  0.1360844 , -0.2890829 

In [5]:
model.compile(loss='mean_squared_error', optimizer='adam')

In [6]:
for _ in range(5):
    model.fit(X_train, y_train, batch_size = 15, epochs = 1, verbose=1)


model.save_weights('weights', save_format='h5')



67/67 [==============================] - 0s 1ms/step - loss: 0.2467


In [1]:
import h5py
hf = h5py.File('weights', 'r+')

In [2]:
list(hf.keys())

['dense', 'dense_1', 'dense_2', 'top_level_model_weights']

In [3]:
a = []
hf.visit(a.append)
print(a)

['dense', 'dense/dense', 'dense/dense/bias:0', 'dense/dense/kernel:0', 'dense_1', 'dense_1/dense_1', 'dense_1/dense_1/bias:0', 'dense_1/dense_1/kernel:0', 'dense_2', 'dense_2/dense_2', 'dense_2/dense_2/bias:0', 'dense_2/dense_2/kernel:0', 'top_level_model_weights']


In [ ]:
hf.close()

In [10]:
arr = np.array(hf['dense_1/dense_1/kernel:0'])

In [11]:
print(arr)

[[ 0.21091138  0.24533753  0.23165822 -0.27847084  0.26929978]
 [ 0.15186447  0.2310069   0.26374274 -0.24854128  0.23394798]
 [-0.38414374 -0.3470676  -0.3360146   0.2916963  -0.27829722]
 [-0.3294085  -0.33712414 -0.29864788  0.2486087  -0.31739637]
 [ 0.14373732  0.21956322  0.1360844  -0.2890829   0.28210488]]


In [12]:
new = np.random.normal(-0.3, 0.3, size=(arr.shape[0], 1))

In [13]:
print(new)

[[-0.27082041]
 [-0.55167372]
 [-0.55973761]
 [ 0.13040608]
 [-0.11083461]]


In [14]:
verynew = np.append(arr, new, axis = 1)

In [15]:
print(verynew)

[[ 0.21091138  0.24533753  0.23165822 -0.27847084  0.26929978 -0.27082041]
 [ 0.15186447  0.23100691  0.26374274 -0.24854128  0.23394798 -0.55167372]
 [-0.38414374 -0.34706759 -0.3360146   0.29169631 -0.27829722 -0.55973761]
 [-0.3294085  -0.33712414 -0.29864788  0.24860869 -0.31739637  0.13040608]
 [ 0.14373732  0.21956322  0.13608439 -0.28908291  0.28210488 -0.11083461]]


In [16]:
print(arr)
print(verynew)

[[ 0.21091138  0.24533753  0.23165822 -0.27847084  0.26929978]
 [ 0.15186447  0.2310069   0.26374274 -0.24854128  0.23394798]
 [-0.38414374 -0.3470676  -0.3360146   0.2916963  -0.27829722]
 [-0.3294085  -0.33712414 -0.29864788  0.2486087  -0.31739637]
 [ 0.14373732  0.21956322  0.1360844  -0.2890829   0.28210488]]
[[ 0.21091138  0.24533753  0.23165822 -0.27847084  0.26929978 -0.27082041]
 [ 0.15186447  0.23100691  0.26374274 -0.24854128  0.23394798 -0.55167372]
 [-0.38414374 -0.34706759 -0.3360146   0.29169631 -0.27829722 -0.55973761]
 [-0.3294085  -0.33712414 -0.29864788  0.24860869 -0.31739637  0.13040608]
 [ 0.14373732  0.21956322  0.13608439 -0.28908291  0.28210488 -0.11083461]]


In [18]:
del hf['dense_1/dense_1/kernel:0']

In [19]:
newdata = hf.create_dataset("dense_1/dense_1/kernel:0", (5, 6), maxshape = (100, 100), data = verynew)

In [20]:
b = []
hf.visit(b.append)
print(b)

['dense', 'dense/dense', 'dense/dense/bias:0', 'dense/dense/kernel:0', 'dense_1', 'dense_1/dense_1', 'dense_1/dense_1/bias:0', 'dense_1/dense_1/kernel:0', 'dense_2', 'dense_2/dense_2', 'dense_2/dense_2/bias:0', 'dense_2/dense_2/kernel:0', 'top_level_model_weights']


In [21]:
print(a)
print(b)

['dense', 'dense/dense', 'dense/dense/bias:0', 'dense/dense/kernel:0', 'dense_1', 'dense_1/dense_1', 'dense_1/dense_1/bias:0', 'dense_1/dense_1/kernel:0', 'dense_2', 'dense_2/dense_2', 'dense_2/dense_2/bias:0', 'dense_2/dense_2/kernel:0', 'top_level_model_weights']
['dense', 'dense/dense', 'dense/dense/bias:0', 'dense/dense/kernel:0', 'dense_1', 'dense_1/dense_1', 'dense_1/dense_1/bias:0', 'dense_1/dense_1/kernel:0', 'dense_2', 'dense_2/dense_2', 'dense_2/dense_2/bias:0', 'dense_2/dense_2/kernel:0', 'top_level_model_weights']


In [22]:
arr = np.array(hf['dense_1/dense_1/kernel:0'])

In [23]:
print(arr)

[[ 0.21091138  0.24533753  0.23165822 -0.27847084  0.26929978 -0.27082041]
 [ 0.15186447  0.23100691  0.26374274 -0.24854128  0.23394798 -0.55167372]
 [-0.38414374 -0.34706759 -0.3360146   0.29169631 -0.27829722 -0.55973761]
 [-0.3294085  -0.33712414 -0.29864788  0.24860869 -0.31739637  0.13040608]
 [ 0.14373732  0.21956322  0.13608439 -0.28908291  0.28210488 -0.11083461]]


In [24]:
del hf['dense_1/dense_1/bias:0']

In [25]:
newdata = hf.create_dataset("dense_1/dense_1/bias:0", (6, ), maxshape = (100, ))

In [26]:
print(a)
print(b)

['dense', 'dense/dense', 'dense/dense/bias:0', 'dense/dense/kernel:0', 'dense_1', 'dense_1/dense_1', 'dense_1/dense_1/bias:0', 'dense_1/dense_1/kernel:0', 'dense_2', 'dense_2/dense_2', 'dense_2/dense_2/bias:0', 'dense_2/dense_2/kernel:0', 'top_level_model_weights']
['dense', 'dense/dense', 'dense/dense/bias:0', 'dense/dense/kernel:0', 'dense_1', 'dense_1/dense_1', 'dense_1/dense_1/bias:0', 'dense_1/dense_1/kernel:0', 'dense_2', 'dense_2/dense_2', 'dense_2/dense_2/bias:0', 'dense_2/dense_2/kernel:0', 'top_level_model_weights']


In [27]:
del hf['dense_2/dense_2/kernel:0']

In [28]:
newdata = hf.create_dataset("dense_2/dense_2/kernel:0", (6, 1), maxshape = (100, 100))

In [29]:
hf.close()